<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="testcases.TC001_LoginAndLogout" tests="3" time="43.019" ignored="3" failures="0" timestamp="24 Mar 2018 04:55:50 GMT" skipped="0" hostname="Vinay" errors="3">
  <testcase name="loginAndLogout" time="18.997" classname="testcases.TC001_LoginAndLogout">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
	at utils.Reporter.reportStep(Reporter.java:61)
	at utils.Reporter.reportStep(Reporter.java:71)
	at wdMethods.SeMethods.type(SeMethods.java:120)
	at pages.LoginPage.enterUserName(LoginPage.java:28)
	at testcases.TC001_LoginAndLogout.loginAndLogout(TC001_LoginAndLogout.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
]]>
    </error>
  </testcase> <!-- loginAndLogout -->
  <testcase name="afterMethod" time="22.553" classname="testcases.TC001_LoginAndLogout">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
	at utils.Reporter.reportStep(Reporter.java:61)
	at wdMethods.SeMethods.closeAllBrowsers(SeMethods.java:385)
	at wdMethods.ProjectMethods.afterMethod(ProjectMethods.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
]]>
    </error>
  </testcase> <!-- afterMethod -->
  <testcase name="loginAndLogout" time="1.469" classname="testcases.TC001_LoginAndLogout">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
	at utils.Reporter.reportStep(Reporter.java:61)
	at utils.Reporter.reportStep(Reporter.java:71)
	at wdMethods.SeMethods.type(SeMethods.java:120)
	at pages.LoginPage.enterUserName(LoginPage.java:28)
	at testcases.TC001_LoginAndLogout.loginAndLogout(TC001_LoginAndLogout.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
]]>
    </error>
  </testcase> <!-- loginAndLogout -->
  <testcase name="afterTest" classname="wdMethods.ProjectMethods">
    <skipped/>
  </testcase> <!-- afterTest -->
  <testcase name="beforeSuite" classname="wdMethods.ProjectMethods">
    <skipped/>
  </testcase> <!-- beforeSuite -->
  <testcase name="afterSuite" classname="wdMethods.ProjectMethods">
    <skipped/>
  </testcase> <!-- afterSuite -->
</testsuite> <!-- testcases.TC001_LoginAndLogout -->
